### ISSUE TITLE
1 GPIO pin for button working, but the others don't work - Lilygo T5 4.7 v2.3 

### ISSUE THREAD

**Issue by WebSpruce** [Xinyuan-LilyGO/LilyGo-EPD47#123]
Hello,
I have a question about correct GPIO pins for buttons in lilygo t5 4.7 v2.3.

I already have working first button with GPIO21, but I'd like to get access to others

On the store page there is info about pins like GPIO21 that I used and it worked, but another example GPIO00 for second button didn't work.

my current code in .yaml file (EspHome):
```
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO21 
    name: "${esp_name} Button 1"
    on_press:
      then:
      - logger.log: "Single click detected!"
      - display.page.show_next: t5_display
      - component.update: t5_display
  - platform: gpio
    pin:
      number: GPIO00
    name: "${esp_name} Button 2"
    on_press:
      then:
      - logger.log: "Single click second button detected!"
  ```
I don't see any message in log from second button.

Thanks.
